import assert from "node:assert/strict";
import { readFile, access } from "node:fs/promises";
import test from "node:test";
const read = name => readFile(new URL("../" + name, import.meta.url), "utf8");
test("all migrated controls live once in the new shell without legacy assets", async () => {
  const shell = await read("public/index.html");
  const panels = await read("ui/workspace/panels.html");
  const app = await read("ui/workspace/features.js");
  const styles = await read("public/journey/workspace.css");
  const html = shell + panels;
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
  assert.equal(new Set(ids).size, ids.length, "No duplicate DOM IDs or forms");
  for (const [, id] of app.matchAll(/querySelector\("#([A-Za-z][\w-]*)"\)/g)) assert.ok(ids.includes(id), `Missing #${id}`);
  for (const area of ["journey", "desk", "library", "owner"]) assert.match(shell, new RegExp(`data-area="${area}"`));
  const surfaces = [...panels.matchAll(/data-surface="([^"]+)"/g)].map(match => match[1]);
  assert.equal(surfaces.length, 16);
  assert.equal(new Set(surfaces).size, 16);
  const fields = JSON.parse(await read("public/journey/fields.json"));
  const inputs = [...panels.matchAll(/data-(?:deal|profile)-field="([^"]+)"/g)].map(match => match[1]);
  assert.deepEqual(inputs.sort(), Object.keys(fields).sort(), "All 103 feature controls retained exactly once");
  assert.equal([...panels.matchAll(/data-dcf-comparable=/g)].length, 3);
  assert.equal([...panels.matchAll(/data-context-reset=/g)].length, 3);
  assert.doesNotMatch(html, /<iframe|src="\/app.js"|href="\/styles.css"|id="workspaceLink"/);
  await assert.rejects(access(new URL("../public/app.js", import.meta.url)));
  await assert.rejects(access(new URL("../public/styles.css", import.meta.url)));
  assert.match(styles, /\[hidden\]\s*\{\s*display:\s*none\s*!important/);
  assert.match(styles, /\.contextCoreMode \.contextAdvanced\s*\{\s*display:\s*none/);
  assert.match(styles, /prefers-reduced-motion/);
  let depth = 0;
  for (const char of styles) { if (char === "{") depth++; if (char === "}") depth--; assert.ok(depth >= 0); }
  assert.equal(depth, 0);
});
test("unified workspace retains feature behavior and backend safeguards", async () => {
  const app = await read("ui/workspace/features.js");
  const server = await read("server.js");
  const storage = await read("storage.js");
  assert.match(app, /async function loadSessionHistory\(\)/, "The browser must load resumable conversation threads.");
  assert.match(app, /function setInteractionBusy\(busy\)/, "Concurrent chat and analysis actions need one interaction lock.");
  assert.match(app, /function brandVisibleText[\s\S]*?EstateLab[\s\S]*?Jarvis/, "Rendered text must scrub legacy branding from retrieved knowledge.");
  assert.match(app, /return brandVisibleText\(lines\.join\("\\n"\)\)/, "Copied deal reports must scrub legacy branding too.");
  assert.match(app, /FRAMEWORK ONLY/, "Framework fallback responses need an explicit badge.");
  assert.match(app, /FRAMEWORK \+ AI/, "External reasoning responses need a model-neutral badge.");
  assert.doesNotMatch(app, /FRAMEWORK \+ DEEPSEEK|modelLabel\(/, "The frontend must not expose a specific reasoning model.");
  assert.match(app, /result\.memoryCandidate/, "The chat must surface memory candidates for review.");
  assert.match(app, /contextCoachMarkup\(intelligence\.contextCoach\)/, "Chat replies need the v5.2 next-move coach.");
  assert.match(app, /data-coach-prompt/, "V5.2 next-move prompts must be clickable from chat.");
  assert.doesNotMatch(app, /renderContextReadiness|data-readiness-panel|renderExperienceLock/, "The retired readiness-chip and experience-lock renderers must stay consolidated into the Deal Journey.");
  assert.match(app, /function openJourneyPanel[\s\S]*?focusFirstMissingContextField\(panelName\)/, "Journey panel steps must open the right card and focus missing context.");
  assert.match(app, /function handleJourneyAction[\s\S]*?runDealScreening\(\)[\s\S]*?runDealAnalysis\(\)[\s\S]*?openShortlistPanel\(\)/, "Journey actions must route to existing screen, analyse, and compare flows.");
  assert.match(app, /function renderOwnerIntelligence[\s\S]*?ownerIntelLanes[\s\S]*?ownerIntelCoverage/, "Owner intelligence must render coverage lanes and project-level coverage rows.");
  assert.match(app, /function loadOwnerIntelligence[\s\S]*?\/api\/owner\/market\/projects[\s\S]*?\/api\/owner\/development-cases[\s\S]*?\/api\/owner\/documents[\s\S]*?\/api\/owner\/restore\/history[\s\S]*?\/api\/owner\/ops/, "Owner intelligence must unify projects, cases, evidence, owner data safety, and production ops status.");
  assert.match(app, /function loadOwnerResearch[\s\S]*?\/api\/owner\/research\/studies[\s\S]*?function submitOwnerResearchBundle[\s\S]*?replace=true/, "Owner research must load, import, and deliberately replace strict study bundles.");
  assert.match(app, /function importOwnerMarketBatch[\s\S]*?\/api\/owner\/market\/import[\s\S]*?ownerMarketImportForm\.addEventListener/, "The market console must wire bulk JSON imports to the owner import API.");
  assert.match(app, /function ownerIntelCoverageScore[\s\S]*?ownerIntelSnapshot[\s\S]*?renderOwnerIntelCoverageRows/, "Owner intelligence must compute a coverage score and render filtered project rows.");
  assert.match(app, /function ownerIntelBriefText[\s\S]*?APEX OWNER INTELLIGENCE BRIEF[\s\S]*?copyOwnerIntelBrief/, "Owner intelligence must export a copyable operating brief.");
  assert.match(app, /function exportOwnerKnowledgeBackup[\s\S]*?\/api\/owner\/export\?chunks=true[\s\S]*?downloadJsonFile/, "Owner intelligence must download a restorable private owner knowledge backup with chunks.");
  assert.match(app, /ownerBackupMarkerKey[\s\S]*?function ownerBackupReminder[\s\S]*?Backup rhythm/, "Owner intelligence must track local backup rhythm against current owner knowledge.");
  assert.match(app, /function recordOwnerBackupEvent[\s\S]*?\/api\/owner\/backup\/events[\s\S]*?backupHash/, "Owner intelligence must record successful backup downloads in the server ledger.");
  assert.match(app, /function sendOwnerBackupReminder[\s\S]*?\/api\/owner\/backup\/reminder[\s\S]*?ownerIntelBackupReminder/, "Owner intelligence must trigger the backup reminder endpoint from the owner console.");
  assert.match(app, /function renderOwnerOps[\s\S]*?PRODUCTION OPS[\s\S]*?function refreshOwnerOps[\s\S]*?\/api\/owner\/ops/, "Owner intelligence must render and refresh owner-only production readiness.");
  assert.match(app, /function previewOwnerKnowledgeRestore[\s\S]*?\/api\/owner\/restore[\s\S]*?dryRun:\s*true/, "Owner intelligence must validate backup restore files before enabling restore.");
  assert.match(app, /function confirmOwnerKnowledgeRestore[\s\S]*?ownerIntelRestorePhrase\.value\.trim\(\)[\s\S]*?RESTORE OWNER KNOWLEDGE[\s\S]*?\/api\/owner\/restore/, "Owner intelligence restore must require the typed explicit confirmation phrase.");
  assert.match(app, /function loadOwnerRestoreHistory[\s\S]*?\/api\/owner\/restore\/history[\s\S]*?renderOwnerRestoreHistory/, "Owner intelligence must expose restore history and rollback snapshots.");
  assert.match(app, /function rollbackOwnerKnowledgeSnapshot[\s\S]*?ROLLBACK OWNER KNOWLEDGE[\s\S]*?\/api\/owner\/restore\/rollback/, "Owner intelligence rollback must require a typed rollback phrase.");
  assert.match(app, /function loadOwnerAdminUsers[\s\S]*?\/api\/admin\/users[\s\S]*?function saveOwnerAdminUser[\s\S]*?PATCH/, "Owner intelligence must expose owner-token-gated user and plan control.");
  assert.match(app, /data-owner-intel-action="case"[\s\S]*?data-owner-intel-action="signal"[\s\S]*?data-owner-intel-action="proof"/, "Owner intelligence project rows must expose direct case, signal, and proof actions.");
  assert.match(app, /function handleOwnerIntelProjectAction[\s\S]*?openOwnerCasePanel\(\)[\s\S]*?prefillOwnerCaseFromProject[\s\S]*?openOwnerMarketPanel\(\)[\s\S]*?prefillOwnerObservationFromProject[\s\S]*?openOwnerEvidencePanel\(\)[\s\S]*?prefillOwnerEvidenceFromProject/, "Owner intelligence actions must open the right owner workspace and prefill project context.");
  assert.match(app, /contextCoreFieldKeys[\s\S]*?function renderContextAssist[\s\S]*?data-context-field-mode/, "Expanded cards must default to guided essentials before exposing advanced fields.");
  assert.match(app, /function markContextFieldDepth[\s\S]*?contextAdvanced[\s\S]*?applyContextFieldMode/, "Context fields must be classified into core and advanced groups at boot.");
  assert.match(app, /function dealScreeningPrompt[\s\S]*?Run Apex Deal Screening Mode[\s\S]*?Ask at most 3 next questions/, "The quick screening path must generate a short mentor-style prompt from current cards.");
  assert.match(app, /function runDealScreening[\s\S]*?submitQuestion\(dealScreeningPrompt\(\), \{ displayText: "Screen this deal using my current Deal\/Profile cards\." \}\)/, "The quick screening button must keep the displayed chat message clean.");
  assert.match(app, /function detectInputMode[\s\S]*?compare[\s\S]*?offer[\s\S]*?checklist/, "V5.4 must detect smart input intent before send.");
  assert.match(app, /inputMode:\s*inputMode\.id/, "V5.4 must include detected input mode in chat requests.");
  assert.match(app, /function voiceSafeText[\s\S]*?Full answer is on screen/, "V5.5 must shorten spoken replies while preserving the written answer.");
  assert.match(app, /function responseFeedbackMarkup[\s\S]*?data-response-feedback/, "V5.6 needs inline response feedback controls.");
  assert.match(app, /function handleResponseFeedback[\s\S]*?writeResponseFeedback/, "V5.6 feedback controls must save recent answer-shape feedback locally.");
  assert.match(app, /responseFeedback:\s*responseFeedbackSummary\(\)/, "V5.6 must send recent answer feedback into future chat requests.");
  assert.match(server, /responseFeedback[\s\S]*?Recent answer feedback/, "V5.6 feedback must reach the server persona prompt.");
  assert.match(server, /feedbackPrefersShort[\s\S]*?feedbackPrefersWarmer[\s\S]*?feedbackPrefersEvidence/, "V5.6 server persona must translate feedback into answer-shape instructions.");
  assert.match(server, /formatStructuredAnswer[\s\S]*?currentView[\s\S]*?counterCase[\s\S]*?evidenceGaps[\s\S]*?alternativeAngle[\s\S]*?nextSteps/, "V10.5 framework fallbacks must return a complete decision brief.");
  assert.match(server, /Use High confidence only[\s\S]*?current, dated, deal-specific evidence[\s\S]*?under about 220 words/, "External-model instructions must calibrate confidence to evidence and stay concise.");
  assert.match(app, /const voicePreferenceKey[\s\S]*?localStorage\.getItem\(voicePreferenceKey\) === "true"/, "Voice responses must remain off until the user explicitly opts in.");
  assert.match(app, /function answerHeading[\s\S]*?function answerMarkup[\s\S]*?answerSection/, "Structured answers need readable on-screen sections.");
  assert.doesNotMatch(app, /sourceConfidence/, "Source counts must not be presented as synthetic confidence.");
  assert.match(app, /function syncResponseFeedback[\s\S]*?\/api\/memory\/answer-style/, "V5.7 must sync answer-style feedback for signed-in users.");
  assert.match(app, /answerStyle\.feedbackCount/, "V5.7 memory settings must surface account-level answer-style learning.");
  assert.match(server, /function normalizeAnswerStyle[\s\S]*?slice\(0, 40\)/, "V5.7 must keep account answer-style memory compact.");
  assert.match(server, /POST" && url\.pathname === "\/api\/memory\/answer-style"/, "V5.7 needs a protected answer-style memory endpoint.");
  assert.match(server, /approvedAnswerStyleFeedback\(actor\.user\)/, "V5.7 stored answer style must feed future response-persona routing.");
  assert.match(storage, /"answerStyle":\{"version":1,"feedback":\[\]\}/, "V5.7 storage defaults need an empty answer-style memory profile.");
  assert.match(app, /data-response-refine/, "V5.8 needs an inline answer refinement action.");
  assert.match(app, /function responseRefinementPrompt[\s\S]*?Keep the same investment judgment[\s\S]*?Do not change the verdict/, "V5.8 refinement prompts must preserve the original investment judgment.");
  assert.match(app, /function handleResponseRefine[\s\S]*?submitQuestion\(prompt\)/, "V5.8 refinement actions must send a prepared follow-up prompt.");
  assert.match(app, /function sessionBriefText[\s\S]*?APEX ANALYTIC SESSION BRIEF[\s\S]*?latestApexBriefLines/, "V5.9 must build a portable session brief from current context and latest Apex direction.");
  assert.match(app, /function copySessionBrief[\s\S]*?writeClipboardText\(text\)/, "V5.9 session brief must use the shared clipboard fallback.");
  assert.match(app, /sessionBriefBtn\.addEventListener\("click"/, "V5.9 BRIEF action must be wired in the utility bar.");
  assert.match(app, /function openTrustPanel[\s\S]*?classList\.add\("trustOpen"\)/, "V6.0 trust must open as a workspace state.");
  assert.match(app, /function closeTrustPanel[\s\S]*?classList\.remove\("trustOpen"\)/, "V6.0 trust must close as a workspace state.");
  assert.match(app, /trustToggle\.addEventListener\("click"/, "V6.0 trust action must be wired.");
  assert.match(app, /trustBoundaryKey\s*=\s*"apex\.trustBoundary\.accepted\.v1"/, "V6.1 trust acknowledgement must persist locally.");
  assert.match(app, /function requireTrustBoundary[\s\S]*?openTrustPanel\(action\)/, "V6.1 must route blocked formal reports into the inline trust workspace.");
  assert.match(app, /function acceptTrustBoundary[\s\S]*?version:\s*"v6\.1"[\s\S]*?runDealAnalysis\(\)/, "V6.1 acceptance must continue a pending deal analysis.");
  assert.match(app, /if \(!requireTrustBoundary\("deal-analysis"\)\) return;/, "The Analyse flow must require trust acknowledgement.");
  assert.match(app, /function trustStampMarkup[\s\S]*?V6\.2 REPORT TRUST STAMP/, "V6.2 must render a trust stamp inside formal reports.");
  assert.match(app, /function trustStampText[\s\S]*?Report trust boundary/, "V6.2 must include trust boundary text in copied exports.");
  assert.match(app, /analysisExportText[\s\S]*?\.\.\.trustStampText\(\)/, "Copied deal reports must carry the trust stamp.");
  assert.match(app, /trustStampMarkup\(\)[\s\S]*?<div class="analysisOverview">/, "On-screen deal reports must show the trust stamp before detailed scoring.");
  assert.match(app, /function professionalReviewPack[\s\S]*?Lawyer[\s\S]*?Banker[\s\S]*?Management \/ JMB/, "V6.3 must derive named professional review lanes.");
  assert.match(app, /function professionalReviewMarkup[\s\S]*?V6\.3 PROFESSIONAL REVIEW/, "V6.3 must render a professional review checklist inside formal reports.");
  assert.match(app, /function professionalReviewText[\s\S]*?Professional review checklist/, "V6.3 must include professional review handoff text in copied exports.");
  assert.match(app, /analysisExportText[\s\S]*?\.\.\.professionalReviewText\(analysis\)/, "Copied deal reports must carry the V6.3 professional review checklist.");
  assert.match(app, /trustStampMarkup\(\)[\s\S]*?professionalReviewMarkup\(analysis\)[\s\S]*?<div class="analysisOverview">/, "On-screen deal reports must show trust and professional review before detailed scoring.");
  assert.match(app, /function complianceRefusalMode[\s\S]*?Misleading financing or fund-flow risk[\s\S]*?APEX REFUSES VALIDATION/, "V6.4 must derive unsafe deal refusal mode.");
  assert.match(app, /function complianceRefusalMarkup[\s\S]*?V6\.4 UNSAFE DEAL BOUNDARY/, "V6.4 must render an unsafe deal boundary inside formal reports.");
  assert.match(app, /function commercialGuardrail[\s\S]*?Payment boundary[\s\S]*?Public use/, "V6.5 must derive public confidence and monetization guardrails.");
  assert.match(app, /function commercialGuardrailMarkup[\s\S]*?V6\.5 PUBLIC CONFIDENCE/, "V6.5 must render public confidence guardrails inside formal reports.");
  assert.match(app, /analysisExportText[\s\S]*?\.\.\.complianceRefusalText\(analysis\)[\s\S]*?\.\.\.commercialGuardrailText\(analysis\)/, "Copied deal reports must carry V6.4 and V6.5 guardrails.");
  assert.match(app, /complianceRefusalMarkup\(analysis\)[\s\S]*?professionalReviewMarkup\(analysis\)[\s\S]*?commercialGuardrailMarkup\(analysis\)[\s\S]*?<div class="analysisOverview">/, "On-screen deal reports must show V6.4 and V6.5 before detailed scoring.");
  assert.match(app, /function developmentProfile[\s\S]*?Owner observations[\s\S]*?Supply moat[\s\S]*?Management culture/, "V7.0 must derive a project-level development intelligence profile.");
  assert.match(app, /function developmentProfileMarkup[\s\S]*?V7\.0 DEVELOPMENT PROFILE[\s\S]*?developmentProfileSignals/, "V7.0 must render the development profile inside formal reports.");
  assert.match(app, /function developmentProfileText[\s\S]*?Development intelligence profile/, "Copied deal reports must include V7.0 development intelligence text.");
  assert.match(app, /analysisExportText[\s\S]*?\.\.\.commercialGuardrailText\(analysis\)[\s\S]*?\.\.\.developmentProfileText\(analysis\)/, "Copied deal reports must carry V7.0 after the public confidence guardrail.");
  assert.match(app, /commercialGuardrailMarkup\(analysis\)[\s\S]*?developmentProfileMarkup\(analysis\)[\s\S]*?<div class="analysisOverview">/, "On-screen deal reports must show V7.0 before detailed scoring.");
  assert.match(server, /function buildDevelopmentIntelligence[\s\S]*?V7\.1[\s\S]*?V7\.10/, "V7.1-V7.10 must be derived by the backend development intelligence engine.");
  assert.match(server, /analysis\.developmentIntelligence = buildDevelopmentIntelligence\(analysis\)/, "Formal deal reports must attach the V7 development intelligence stack after owner market matching.");
  assert.match(server, /developmentIntelligence: normalizeReportDevelopmentIntelligence\(analysis\.developmentIntelligence\)/, "Saved private reports must preserve the V7 stack.");
  assert.match(server, /developmentCases: \[\]/, "Knowledge storage must include owner development cases.");
  assert.match(server, /function selectDevelopmentCaseIntelligence[\s\S]*?actionQueue/, "Development case matching must produce summary, score, posture, and action queue.");
  assert.match(server, /function developmentCaseCoverage[\s\S]*?missingManagement[\s\S]*?missingResale/, "The case library must summarize coverage gaps.");
  assert.match(server, /\/api\/owner\/development-cases/, "Owner development cases need a token-gated API.");
  assert.match(server, /analysis\.caseIntelligence = selectDevelopmentCaseIntelligence/, "Formal deal reports must attach matched development case intelligence.");
  assert.match(server, /caseIntelligence: normalizeReportCaseIntelligence\(analysis\.caseIntelligence\)/, "Saved private reports must preserve development case intelligence.");
  assert.match(server, /developmentCaseSources\(analysis\.caseIntelligence\)/, "Matched development cases must appear in formal report sources.");
  assert.match(server, /function buildDocumentIntelligence[\s\S]*?V8\.1[\s\S]*?V8\.10/, "V8.1-V8.10 must be derived by the backend document intelligence engine.");
  assert.match(server, /knowledgeService\.retrieve\(learningQuery,\s*(?:db|database)\.knowledge\.chunks,\s*8,\s*\{\s*allowEmbedding:\s*allowExternalRetrieval\s*\}\)/, "Formal deal reports must retrieve owner documents for V8 evidence matching.");
  assert.match(server, /analysis\.documentIntelligence = buildDocumentIntelligence\(analysis,\s*(?:db|database)\.knowledge,\s*documentEvidenceResult\)/, "Formal deal reports must attach the V8 document intelligence stack.");
  assert.match(server, /documentIntelligence: normalizeReportDocumentIntelligence\(analysis\.documentIntelligence\)/, "Saved private reports must preserve the V8 stack.");
  assert.match(server, /documentEvidenceSources\(analysis\.documentIntelligence\)/, "Matched owner evidence must appear in formal report sources.");
  assert.match(server, /function buildPortfolioCommand[\s\S]*?V9\.1[\s\S]*?V9\.10/, "V9.1-V9.10 must be derived by the backend portfolio command engine.");
  assert.match(server, /analysis\.portfolioCommand = buildPortfolioCommand\(analysis\)/, "Formal deal reports must attach the V9 portfolio command stack.");
  assert.match(server, /portfolioCommand: normalizeReportPortfolioCommand\(analysis\.portfolioCommand\)/, "Saved private reports must preserve the V9 stack.");
  assert.match(server, /function buildFinalCommand[\s\S]*?V10\.1[\s\S]*?V10\.10/, "V10.1-V10.10 must be derived by the backend final command engine.");
  assert.match(server, /analysis\.finalCommand = buildFinalCommand\(analysis\)/, "Formal deal reports must attach the V10 final command stack.");
  assert.match(server, /finalCommand: normalizeReportFinalCommand\(analysis\.finalCommand\)/, "Saved private reports must preserve the V10 stack.");
  assert.match(server, /const DECISION_ENGINE_VERSION = "Apex v10\.10"/, "New formal analyses must expose the V10.10 engine label.");
  assert.match(server, /function ownerKnowledgeExport[\s\S]*?owner-knowledge-backup[\s\S]*?\/api\/owner\/export/, "Owner-controlled knowledge needs a token-gated JSON backup endpoint.");
  assert.match(server, /function ownerKnowledgeRestorePreview[\s\S]*?RESTORE OWNER KNOWLEDGE[\s\S]*?\/api\/owner\/restore/, "Owner-controlled knowledge needs a guarded restore preview endpoint.");
  assert.match(server, /function ownerBackupLedger[\s\S]*?ownerBackupEvents[\s\S]*?\/api\/owner\/backup\/events/, "Owner-controlled backups need a server-side export ledger.");
  assert.match(server, /function ownerBackupReminderStatus[\s\S]*?deliverOwnerBackupReminder[\s\S]*?\/api\/owner\/backup\/reminder/, "Owner-controlled backups need a provider-neutral reminder endpoint.");
  assert.match(server, /function ownerKnowledgeVersionSummary[\s\S]*?currentVersionHash[\s\S]*?\/api\/owner\/restore\/history/, "Owner-controlled restore history must expose safe snapshot summaries and current version fingerprint.");
  assert.match(server, /\/api\/owner\/restore\/rollback[\s\S]*?ROLLBACK OWNER KNOWLEDGE/, "Owner-controlled rollback must require an explicit confirmation phrase.");
  assert.match(app, /function developmentIntelligenceMarkup[\s\S]*?V7\.1 - V7\.10 DEVELOPMENT INTELLIGENCE[\s\S]*?developmentActionQueue/, "V7.1-V7.10 must render as one compact report stack.");
  assert.match(app, /function developmentIntelligenceText[\s\S]*?V7 development intelligence stack/, "Copied reports must include the V7.1-V7.10 stack.");
  assert.match(app, /developmentProfileMarkup\(analysis\)[\s\S]*?developmentIntelligenceMarkup\(analysis\.developmentIntelligence\)[\s\S]*?<div class="analysisOverview">/, "On-screen reports must show the V7 stack before detailed scorecard sections.");
  assert.match(app, /function renderOwnerCases[\s\S]*?\/api\/owner\/development-cases/, "The case library must load owner development cases.");
  assert.match(app, /function ownerCaseGapCount[\s\S]*?ownerCaseCompletenessFilter[\s\S]*?renderOwnerCases\(ownerCaseLastPayload\)/, "The case library must filter incomplete founder case notes locally.");
  assert.match(app, /function saveOwnerCase[\s\S]*?method: editing \? "PATCH" : "POST"/, "The case library must create and edit owner development cases.");
  assert.match(app, /function fillOwnerCaseForm[\s\S]*?ownerCaseSubmit\.textContent = "SAVE CASE"/, "Editing a case must load it into the owner case form.");
  assert.match(app, /data-owner-case-action="edit"/, "Owner development cases need an edit action.");
  assert.match(app, /function caseIntelligenceMarkup[\s\S]*?CASE LIBRARY V1[\s\S]*?caseActionQueue/, "Matched development cases must render as one compact report card.");
  assert.match(app, /function caseIntelligenceText[\s\S]*?Development case library/, "Copied reports must include matched development case intelligence.");
  assert.match(app, /caseIntelligence: analysis\.caseIntelligence/, "Shortlisted deals must preserve matched development case intelligence.");
  assert.match(app, /caseIntelligenceMarkup\(analysis\.caseIntelligence\)/, "On-screen reports must show matched development case intelligence.");
  assert.match(app, /function renderOwnerEvidence[\s\S]*?\/api\/owner\/documents/, "The V8 evidence vault must load owner documents.");
  assert.match(app, /let ownerEvidenceDocuments[\s\S]*?function renderOwnerEvidenceDocuments[\s\S]*?ownerEvidenceFilter\.addEventListener\("input"/, "The evidence vault must filter loaded proof documents without another server request.");
  assert.match(app, /function createOwnerEvidence[\s\S]*?\/api\/owner\/documents/, "The V8 evidence vault must create owner evidence documents.");
  assert.match(app, /function documentIntelligenceMarkup[\s\S]*?V8\.1 - V8\.10 DOCUMENT INTELLIGENCE[\s\S]*?documentActionQueue/, "V8.1-V8.10 must render as one compact report stack.");
  assert.match(app, /function documentIntelligenceText[\s\S]*?V8 document intelligence stack/, "Copied reports must include the V8.1-V8.10 stack.");
  assert.match(app, /developmentIntelligenceMarkup\(analysis\.developmentIntelligence\)[\s\S]*?documentIntelligenceMarkup\(analysis\.documentIntelligence\)[\s\S]*?<div class="analysisOverview">/, "On-screen reports must show the V8 stack before detailed scorecard sections.");
  assert.match(app, /function portfolioCommandMarkup[\s\S]*?V9\.1 - V9\.10 PORTFOLIO COMMAND[\s\S]*?portfolioCommandQueue/, "V9.1-V9.10 must render as one compact report stack.");
  assert.match(app, /function portfolioCommandText[\s\S]*?V9 portfolio command stack/, "Copied reports must include the V9.1-V9.10 stack.");
  assert.match(app, /documentIntelligenceMarkup\(analysis\.documentIntelligence\)[\s\S]*?portfolioCommandMarkup\(analysis\.portfolioCommand\)[\s\S]*?finalCommandMarkup\(analysis\.finalCommand\)[\s\S]*?<div class="analysisOverview">/, "On-screen reports must show the V9 and V10 stacks before detailed scorecard sections.");
  assert.match(app, /function finalCommandMarkup[\s\S]*?V10\.1 - V10\.10 FINAL COMMAND[\s\S]*?finalCommandQueue/, "V10.1-V10.10 must render as one compact final command stack.");
  assert.match(app, /function finalCommandText[\s\S]*?V10 final command stack/, "Copied reports must include the V10.1-V10.10 stack.");
  assert.match(app, /billingGuardrail\.textContent[\s\S]*?never changes scores, hard stops, or recommendations/, "Account billing must state that payment cannot change decisions.");
  assert.match(app, /\/api\/memory\/settings/, "Memory collection and reasoning must be controlled through explicit settings.");
  assert.match(app, /captureEnabled:\s*memoryCaptureEnabled\.checked/, "Memory capture must be opt-in from the UI.");
  assert.match(app, /reasoningEnabled:\s*memoryReasoningEnabled\.checked/, "Using approved memory in reasoning must be opt-in from the UI.");
  assert.match(app, /function renderMemoryProfile/, "V3.1 must render the derived investor memory profile.");
  assert.match(app, /item\.categoryLabel/, "V3.2 memory review queue must show upgraded category labels.");
  assert.match(app, /item\.profileImpact/, "V3.2 memory review queue must explain how each memory affects the profile.");
  assert.match(app, /data-memory-action="approve"/, "Memory candidates must require explicit approval.");
  assert.match(app, /data-analysis-action="report"/, "Every structured analysis needs a printable deal report.");
  assert.match(app, /data-analysis-action="copy"/, "Every structured analysis needs a text copy export.");
  assert.match(app, /decisionFocusMarkup\(analysis\)/, "Deal reports need a single decision-focus explanation.");
  assert.match(app, /dealSnapshotMarkup\(analysis\)[\s\S]*?dcfValuationMarkup\(analysis\.residentialDcf\)[\s\S]*?decisionFocusMarkup\(analysis\)/, "Formal reports must place the optional DCF screen near the deal snapshot.");
  assert.match(app, /function collectDcfComparables[\s\S]*?completed transaction/, "DCF comparable inputs must be structured as completed transactions.");
  assert.match(app, /\/api\/tools\/residential-dcf\/workbook/, "The browser must download an auditable DCF workbook from the server.");
  assert.match(app, /personalizedChallengeMarkup\(analysis\.personalizedChallenge\)/, "V3.3 deal reports need a separate personalized challenge card.");
  assert.match(app, /readinessMarkup\(analysis\.investorReadiness\)/, "Deal reports need an investor readiness summary.");
  assert.match(app, /productExperienceMarkup\(analysis\.productExperience\)/, "Deal reports need the v5 product-experience guidance summary.");
  assert.match(app, /evidenceChecklistMarkup\(analysis\.evidenceChecklist/, "Deal reports need an evidence checklist.");
  assert.match(app, /evidenceEngineMarkup\(analysis\.evidenceEngine\)/, "Deal reports need v4.0 evidence engine.");
  assert.match(app, /transactionComparableMarkup\(analysis\.transactionComparableEvidence\)/, "Deal reports need v4.1 transaction comparable evidence.");
  assert.match(app, /achievedRentalMarkup\(analysis\.achievedRentalEvidence\)/, "Deal reports need v4.2 achieved rental evidence.");
  assert.match(app, /financingValuationMarkup\(analysis\.financingValuationEvidence\)/, "Deal reports need v4.3 financing and valuation evidence.");
  assert.match(app, /supplyAbsorptionMarkup\(analysis\.supplyAbsorptionEvidence\)/, "Deal reports need v4.4 supply and absorption evidence.");
  assert.match(app, /siteManagementMarkup\(analysis\.siteManagementEvidence\)/, "Deal reports need v4.5 site and management evidence.");
  assert.match(app, /legalTransactionMarkup\(analysis\.legalTransactionEvidence\)/, "Deal reports need v4.6 legal and transaction evidence.");
  assert.match(app, /dueDiligenceMarkup\(analysis\.dueDiligencePlan\)/, "Deal reports need a due-diligence task pack.");
  assert.match(app, /stressEnvelopeMarkup\(analysis\.stressEnvelope\)/, "Deal reports need v1.6 stress envelope.");
  assert.match(app, /portfolioGateMarkup\(analysis\.portfolioGate\)/, "Deal reports need v1.7 portfolio expansion gate.");
  assert.match(app, /marketPulseMarkup\(analysis\.marketPulse\)/, "Deal reports need v1.8 market cycle and liquidity pulse.");
  assert.match(app, /holdExitPlanMarkup\(analysis\.holdExitPlan\)/, "Deal reports need v1.9 hold, refinance, and exit plan.");
  assert.match(app, /decisionSealMarkup\(analysis\.decisionSeal\)/, "Deal reports need v1.10 decision seal.");
  assert.match(app, /v2WorkflowMarkup\("V2\.1 SITE VISIT ASSISTANT", analysis\.siteVisitAssistant/, "Deal reports need v2.1 site visit assistant.");
  assert.match(app, /v2WorkflowMarkup\("V2\.2 SOURCING \/ PROFESSIONAL FILTER", analysis\.sourcingProfessional/, "Deal reports need v2.2 sourcing and professional filter.");
  assert.match(app, /v2WorkflowMarkup\("V2\.3 TENANT \/ RENTAL PLAN", analysis\.tenantRentalPlan/, "Deal reports need v2.3 tenant and rental plan.");
  assert.match(app, /v2WorkflowMarkup\("V2\.4 EXIT STRATEGY", analysis\.exitStrategy/, "Deal reports need v2.4 exit strategy.");
  assert.match(app, /executionPlanMarkup\(analysis\.executionPlan\)/, "Deal reports need v1.5 execution calibration.");
  assert.match(app, /learningLoopMarkup\(analysis\.learningLoop\)/, "Deal reports need visible private learning signals when available.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.4 DEAL MEMORY COMPARISON", analysis\.dealMemoryComparison/, "Deal reports need v3.4 saved deal comparison.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.5 BELIEF TRACKER", analysis\.beliefTracker/, "Deal reports need v3.5 belief tracking.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.6 SOURCE TRANSPARENCY", analysis\.sourceTransparency/, "Deal reports need v3.6 source transparency.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.7 MEMORY CONFLICTS", analysis\.memoryConflicts/, "Deal reports need v3.7 memory conflict handling.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.8 PERSONAL OPERATING RULES", analysis\.personalOperatingRules/, "Deal reports need v3.8 operating rules.");
  assert.match(app, /function shortlistRankScore/, "The shortlist must rank deals using an adjusted comparison score.");
  assert.match(app, /shortlistSummaryMarkup\(items\)/, "The shortlist must render a comparison summary.");
  assert.match(app, /recommendationBlockers: analysis\.recommendationBlockers/, "Shortlisted deals must preserve decision blockers for comparison.");
  assert.match(app, /decisionFocus: analysis\.decisionFocus/, "Shortlisted deals must preserve decision focus for comparison.");
  assert.match(app, /personalizedChallenge: analysis\.personalizedChallenge/, "Shortlisted deals must preserve V3.3 personalized challenge context.");
  assert.match(app, /productExperience: analysis\.productExperience/, "Shortlisted deals must preserve V5 product-experience context.");
  assert.match(app, /learningLoop: analysis\.learningLoop/, "Shortlisted deals must preserve learning signals for comparison.");
  assert.match(app, /evidenceEngine: analysis\.evidenceEngine/, "Shortlisted deals must preserve V4.0 evidence engine.");
  assert.match(app, /transactionComparableEvidence: analysis\.transactionComparableEvidence/, "Shortlisted deals must preserve V4.1 transaction comparable evidence.");
  assert.match(app, /achievedRentalEvidence: analysis\.achievedRentalEvidence/, "Shortlisted deals must preserve V4.2 achieved rental evidence.");
  assert.match(app, /financingValuationEvidence: analysis\.financingValuationEvidence/, "Shortlisted deals must preserve V4.3 financing and valuation evidence.");
  assert.match(app, /supplyAbsorptionEvidence: analysis\.supplyAbsorptionEvidence/, "Shortlisted deals must preserve V4.4 supply and absorption evidence.");
  assert.match(app, /siteManagementEvidence: analysis\.siteManagementEvidence/, "Shortlisted deals must preserve V4.5 site and management evidence.");
  assert.match(app, /legalTransactionEvidence: analysis\.legalTransactionEvidence/, "Shortlisted deals must preserve V4.6 legal and transaction evidence.");
  assert.match(app, /developmentIntelligence: analysis\.developmentIntelligence/, "Shortlisted deals must preserve the V7 development intelligence stack.");
  assert.match(app, /documentIntelligence: analysis\.documentIntelligence/, "Shortlisted deals must preserve the V8 document intelligence stack.");
  assert.match(app, /portfolioCommand: analysis\.portfolioCommand/, "Shortlisted deals must preserve the V9 portfolio command stack.");
  assert.match(app, /finalCommand: analysis\.finalCommand/, "Shortlisted deals must preserve the V10 final command stack.");
  assert.match(app, /residentialDcf: analysis\.residentialDcf/, "Shortlisted deals must preserve the DCF and comparison screen.");
  assert.match(app, /marketIntelligence: analysis\.marketIntelligence/, "Shortlisted deals must preserve matched owner market intelligence for later comparison.");
  assert.match(app, /dealMemoryComparison: analysis\.dealMemoryComparison/, "Shortlisted deals must preserve V3.4 saved deal comparison.");
  assert.match(app, /beliefTracker: analysis\.beliefTracker/, "Shortlisted deals must preserve V3.5 belief tracking.");
  assert.match(app, /sourceTransparency: analysis\.sourceTransparency/, "Shortlisted deals must preserve V3.6 source transparency.");
  assert.match(app, /memoryConflicts: analysis\.memoryConflicts/, "Shortlisted deals must preserve V3.7 memory conflict handling.");
  assert.match(app, /personalOperatingRules: analysis\.personalOperatingRules/, "Shortlisted deals must preserve V3.8 operating rules.");
  assert.match(app, /analysis\.dimensions/, "Deal results must render separate decision dimensions.");
  assert.match(app, /analysis\.scenarios/, "Deal results must render downside scenarios.");
  assert.match(app, /marketIntelligenceMarkup\(analysis\.marketIntelligence\)/, "Deal results must render matched dated market intelligence.");
  assert.match(app, /type === "market"/, "Market observations need a distinct source label.");
  assert.match(app, /type === "case"/, "Owner development cases need a distinct source label.");
  assert.match(app, /\/api\/billing\/status/, "The account surface must load report entitlements.");
  assert.match(app, /\/api\/reports/, "The report-history surface must use private account storage.");
  assert.match(app, /\/api\/journal/, "The decision journal must use private account storage.");
  assert.match(server, /\/api\/tools\/residential-dcf[\s\S]*?generateResidentialDcfWorkbook/, "The server must expose deterministic DCF calculation and workbook generation.");
  assert.match(app, /\/api\/owner\/market\/projects/, "The v2 market console must load and create owner market projects.");
  assert.match(app, /\/api\/owner\/market\/observations/, "The v2 market console must load and create owner market observations.");
  assert.match(app, /\/api\/owner\/development-cases/, "The owner case library must use the development case API.");
  assert.match(app, /\/api\/owner\/documents/, "The v8 evidence vault must use the owner document API.");
  assert.match(app, /x-estatelab-owner-token/, "Owner market writes must require the owner token header.");
  assert.match(app, /ownerMarketEnabled\s*=\s*Boolean\(status\.ownerMarket\?\.enabled\)/, "The frontend must detect whether the owner market API is enabled.");
  assert.match(app, /data-analysis-action="journal"/, "Saved reports need a direct decision-record action.");
  assert.match(app, /function resetContextCard[\s\S]*?localStorage\.removeItem\(storageKey\)/, "Card reset must clear both visible fields and saved browser context.");
  assert.match(app, /data-context-body="\$\{panelName\}"[\s\S]*?\[data-profile-field\]/, "Resetting Guidance must only clear its own visible fields while preserving the rest of the profile context.");
});
